# Generated by Django 3.2.25 on 2026-06-01 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('bank_account_number', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('annual_salary', django_cryptography.fields.encrypt(models.DecimalField(decimal_places=2, max_digits=12))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
